---

- name: Wait for Viya VMs to be ready
  hosts: [AnsibleController]
  become_user: root
  become: yes
  gather_facts: false
  roles:
    - role: prepare_nodes/wait_for_viya_vms
  tags:
    - wait_for_viya_vms


- name: Set up hosts routing
  hosts: [sas_servers]
  become_user: root
  become: yes
  gather_facts: false
  roles:
    - role: prepare_nodes/set_host_routing
  tags:
    - set_host_routing


- name: Log into each VM once,to avoid "unknown host" interactive message
  hosts: [AnsibleController]
  gather_facts: false
  roles:
    - role: prepare_nodes/initialize_known_hosts
  tags:
    - initialize_known_hosts


- name: Create saswork dir
  hosts: [ProgrammingServicesServers]
  become_user: root
  become: yes
  gather_facts: true
  roles:
    - role: prepare_nodes/mount_disk
  tags:
    - create_saswork_dir

- name: Mount sas install dir
  hosts: [NeedMountSASInstallDrive]
  become_user: root
  become: yes
  gather_facts: true
  roles:
    - role: prepare_nodes/mount_disk
      when: SAS_INSTALL_DISK | default()
  tags:
    - mount_sas_install_dir
  vars:
    - MOUNT_DIR: "{{ SAS_INSTALL_DIR }}"
    - MOUNT_DISK: "{{ SAS_INSTALL_DISK }}"


- name: Mount userlib dir
  hosts: [NeedMountUserlibDrive]
  become_user: root
  become: yes
  gather_facts: true
  roles:
    - role: prepare_nodes/mount_disk
      when: USERLIB_DISK | default()
  tags:
    - mount_userlib_dir
  vars:
    - MOUNT_DIR: "{{ USERLIB_DIR }}"
    - MOUNT_DISK: "{{ USERLIB_DISK }}"





